[package]
name = "bech32-utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bech32 = "0.9.1"
clap = {version = "4.4.7", features = ["derive"]}
cosmwasm-std = "1.3.0"
